- .fixtures.yml
- .sync.yml
- manifests/init.pp
- manifests/zone.pp
- spec/defines/dns_zone_spec.rb
- spec/lib/module_spec_helper.rb
- spec/spec_helper.rb
- templates/named.zone.erb
This now requires the dns class is included when using dns::zone instead of loading it if needed. It also moves more variables to parameters.
Lastly it includes lint cleanups needed for https://github.com/theforeman/puppet-dns/pull/27
This would be a major version bump, but IMHO a good one.
> Refactor dns::zone

- manifests/zone.pp
- spec/defines/dns_zone_spec.rb
I can't find anything in RFCs for that requirement and am even running DNS servers myself with zones that have SOAs in other zones.
> remove check if SOA record is in the same zone

- manifests/init.pp
- manifests/params.pp
- templates/options.conf.erb
Allows a user to enable recursion on bind in the global level. useful for situation where multiple networks require access to a single server used as a full DNS server (not just for local zones).
> allow user to control allow-recursion on the global level

- manifests/init.pp
- manifests/params.pp
- manifests/zone.pp
- templates/named.zone.erb
- templates/options.conf.erb
I added diverse options for bind that can be necessary to manage your own DNS :
- recursion
- allow_query
- dnssec_enable
- dnssec_validation
And also the possibility to not create a zone file when you declare a zone (only add an entry in the conf file)
An finally, I adapted the templates.
> Add options and zone possibilities

- manifests/init.pp
- manifests/params.pp
- spec/classes/dns_init_spec.rb
- templates/options.conf.erb
That option allows you to forward requests of PTR records of RFC1918
IP addresses.
> Add the ability to set empty-zones-enable

- manifests/params.pp
- spec/classes/dns_init_spec.rb
This doesn't turn the server into an open recursor by default and
matches the defaults introduced in BIND 9.4.1-P1.
https://kb.isc.org/article/AA-00269/0/What-has-changed-in-the-behavior-of-allow-recursion-and-allow-query-cache.html
Reported in https://github.com/theforeman/puppet-dns/pull/49 by @kmcfate
> Limit recursion to localnets and localhost

- manifests/params.pp
- spec/classes/dns_init_spec.rb
Set default path for zones.conf to /etc/named/zones.conf to allow easier use of named with chroot enabled
I don't like the fact that existing systems will have /etc/zones.conf left behind unless a site was passing the `publicviewpath` parameter.  Wasn't sure how to best handle changing default path.
> Change default path for zones.conf to /etc/named/zones.conf for RedHat

- manifests/config.pp
- spec/classes/dns_init_spec.rb
The net effect of this change is zero - it's backwards compatible
and does not result in any change for users.
The concat resources create the files with the same permissions
and the concat fragments take care of inserting the templates with
the same feature to override the template if need be.
However, since concat is now used, consumers of puppet-dns can now
insert their own concat fragments without having to maintain their
own template.
Before this change, if we wanted to diverge slightly from the
template, we would need to "fork" the template and maintain our own.
We could otherwise edit the file with resources like file_line but
this is not idempotent.
Spec test coverage for these bits have been improved a bit and
standardized as part of the commit.
> Use concat fragments instead of file resource templates for config

- manifests/init.pp
- manifests/params.pp
- spec/classes/dns_init_spec.rb
- templates/options.conf.erb
- adds a hash parameter to allow additional global options to be added to options.conf
> allow additional_options

- spec/classes/dns_init_spec.rb
- templates/options.conf.erb
The listen-on-v6 parameter would always be configured in
options.conf. This makes it unflexible with the use case of making
BIND listen on another port than 53.
Make it so the configuration is added only when the parameter is set
so that, if required, a user can set listen_on_v6 to false and add
his own configuration in additional_options.
Closes: #67
> Do not configure listen-on-v6 parameter if it's not set

- LICENSE
- README.md
The commit history shows the module has always been under the ASL-2.0,
and that the README text was an inconsistency in 999eb91 where the
LICENSE document was added and README.md was extended (probably from a
template).
Updated the main LICENSE document to include the full text, not only the
boilerplate copyright statement.
Fixes GH-66
> Change licence text in README to match LICENSE/metadata

- manifests/init.pp
- manifests/params.pp
- spec/classes/dns_init_spec.rb
- templates/named.conf.erb
As discussed in https://github.com/theforeman/puppet-dns/pull/72 here comes a version with a loop inside the template which injects the `additional_directives` content into named.conf.
> add additional_directives parameter for top-scope bind directives in named.conf

- manifests/config.pp
- manifests/init.pp
To match style guide and for compatibility with puppet-lint 2.2.0.
> Move chaining arrows to right operand line

- manifests/init.pp
Corrects two parameters to the more specific type from the docs, and
permits any data in `additional_options` to match usage in existing
tests.
> Remove duplicated data type from parameter documentation

- manifests/init.pp
- manifests/params.pp
- spec/classes/dns_init_spec.rb
This allows creating additional zones through a parameter. This can be useful when using hiera.
> Fixes #20555: Add a zones parameter

- manifests/init.pp
- spec/classes/dns_init_spec.rb
This prevents a cyclic dependency when using the zones parameter.
> Use contain for chaining

- README.md
- manifests/key.pp
- manifests/zone.pp
- spec/defines/dns_key_spec.rb
- spec/defines/dns_zone_spec.rb
- templates/key.erb
- templates/named.zone.erb
Fixes GH-94
This commit adds a new resource type key, which creates a rndc key which can be used to control bind using nsupdate.
Also this commit allows to specify update policy rules for zones.
I see that the beaker tests are failing and I also have not written a beaker test for this one.
Please let me know a beaker test is required.
> Adds control keys and specifying update policy

- manifests/init.pp
- manifests/params.pp
- spec/classes/dns_init_spec.rb
Thanks to #108 we can use custom keys :+1: 
We wanted to take it a step further and use the same method for the keys that exists for the zones: `create_resources` via a hash.
This PR achieves this.
Thanks to [Erasys GmbH](http://www.erasys.de/) for their support
> feat: add keys parameter and create_resources accordingly

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/dns_init_spec.rb
Add class parameter dns::group_manage which defaults to true, so that
the module keeps managing the system group for BIND ("bind" or "named"),
but allow the user to set it to false. This way the group can be managed
outside of this module's scope.
Fixes GH-140
> Make managing BIND system group optional

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/dns_init_spec.rb
- templates/sysconfig.Debian.erb
- templates/sysconfig.RedHat.erb
Debian and RedHat allow setting startup options and other settings via a
sysconfig/default file (/etc/default/bind9 under Debian and
/etc/sysconfig/named under RedHat). FreeBSD/DragonFly and ArchLinux
don't have a direct equivalent.
This change allows managing sysconfig/default settings under Debian and
RedHat. It is especially useful for setting startup options like `-4` to
disable IPv6 support in named, or setting the debug level with `-d`. The
change adds a few specific `$dns::sysconfig_*` parameters to model the
default behaviour under Debian and RedHat, as well as a
`$dns::sysconfig_additional_settings` hash parameter that allows setting
arbitrary key-value pairs in the sysconfig file.
For FreeBSD/DragonFly and ArchLinux these parameters are all set to
undef and not used anywhere …
> Add support for managing sysconfig settings

- manifests/init.pp
- manifests/params.pp
- manifests/service.pp
- spec/classes/dns_init_spec.rb
By default the service resource that manages the BIND service will
restart the service when notified by configuration changes. This can be
disruptive.
This change allows the user to set a custom restart command via
`dns::service_restart_command` for the service resource, such as
`/usr/sbin/service bind9 reload` or `/bin/systemctl reload bind9.service`
or even `/usr/sbin/rndc reload`, to avoid restarting the whole named
process. By default no restart command is set.
> Allow setting service restart command

- manifests/config.pp
- manifests/params.pp
- manifests/view.pp
- spec/classes/dns_init_spec.rb
Make use of the `validate_cmd` parameter in concat to run
named-checkconf on the target file. This way the validity of to-be-updated
configuration files named.conf or zones.conf is checked before actually
writing the new configuration and restarting the named service. This
prevents named from loading invalid configuration settings that would
result in named failing to start.
The file named.conf.options itself cannot be checked with
named-checkconf because its content is only valid inside the
"options { };" directive.
> Validate named.conf and zones.conf using named-checkconf

- manifests/init.pp
- manifests/key.pp
- manifests/params.pp
- manifests/service.pp
- manifests/view.pp
- manifests/zone.pp
- spec/classes/dns_init_spec.rb
- spec/defines/dns_zone_spec.rb
This allows users to decide whether the module should manage the
dns service. The check defaults to true, but in case users want to
manage the service autonomously they can.
This also solves "duplicate declaration" issues when the service
is declared in another .pp file
This does not influence package installation.
> Add manage_service parameter

- .sync.yml
- .travis.yml
Due to a bug in Docker CE named can't be started because it messes up
the cgroups.
> Test on CentOS 6 instead of CentOS 7

- manifests/zone.pp
- spec/acceptance/dns_spec.rb
- spec/acceptance/views_spec.rb
- spec/classes/dns_init_spec.rb
- spec/defines/dns_key_spec.rb
- spec/defines/dns_view_spec.rb
- spec/defines/dns_zone_spec.rb
- templates/zone.header.erb
This makes the $soaip parameter optional since in many cases it doesn't makes sense. It was also breaking hard on IPv6-only systems. For those setups the $soaipv6 parameter is also added. The types are also tightened to the correct address family.
> Refactor soaip in dns::zone

- manifests/zone.pp
- spec/defines/dns_zone_spec.rb
- templates/named.zone.erb
- types/updatepolicy.pp
This is part of https://github.com/theforeman/puppet-dns/issues/156. I submit it separately from the other zone options I want to introduce, because this PR might be a breaking change for some installations.
> Make zone update_policy_rules more generic

- manifests/zone.pp
`update_policy_rules` was removed some time ago but I still found a reference to its usage in the zone.pp puppet-strings documentation.
This PR updates the docs parameter as well as adding all the other missing ones (even though it doesn't define them, it's better than nothing ;-) ).
Thanks to [Erasys GmbH](https://erasys.de) for their support
> Update zone documentation

- manifests/config.pp
- manifests/install.pp
- manifests/key.pp
When defining a custom key, the configuration validation would fail on the first run as the configuration would be updated and the validation would run before the key was created.  The error would go away on the second run as the file would then exist before the configuration was updated (from the previous run).  The updated ordering in `dns::key` makes this now work on the first run without an error.
As a note, the `group` creation needed to be moved out of `dns::config` to prevent a dependency cycle.
> Fix custom key ordering

- README.md
- manifests/config.pp
- manifests/init.pp
- manifests/logging.pp
- manifests/logging/category.pp
- manifests/logging/channel.pp
- manifests/params.pp
- spec/acceptance/logging_spec.rb
- spec/classes/dns_init_spec.rb
- spec/defines/dns_logging_category_spec.rb
- spec/defines/dns_logging_channel_spec.rb
- templates/log.category.conf.erb
- templates/log.channel.conf.erb
There was no way in the current settings to configure a log directory or an advanced logging configuration using channels and categories.  This change adds the necessary configuration options and template changes to create a full-featured logging configuration.  README and spec changes have been completed to document and test the change.
> Add the ability to define logging

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/dns_init_spec.rb
I was having the same issue as described in #164 so I added this so the checks could be turned off if needed.
> Allow configuration checks to be turned off

- manifests/config.pp
- manifests/key.pp
- spec/classes/dns_init_spec.rb
With bind-9.13.0+[1], -r option is deprecated and raises
error if passed. With earlier versions of bind also -r
option is optional and in it's absense there are default
function which provides random bytes. So let's drop the
-r option.
Fixes GH-189
[1] https://github.com/isc-projects/bind9/commit/3a4f820
> Drop usage of -r from rndc-confgen

- lib/puppet/functions/dns/reverse_dns.rb
- lib/puppet/functions/get_in_addr_arpa.rb
- lib/puppet/parser/functions/get_in_addr_arpa.rb
- spec/functions/reverse_dns_spec.rb
The get_in_addr_arpa function did not support IPv6. Its implementation was also the old legacy function API. This replacement also has tests, data types and documentation.
> Replace get_in_addr_arpa with reverse_dns function

- manifests/zone.pp
- spec/defines/dns_zone_spec.rb
- templates/named.zone.erb
Allow setting the `dnssec-policy` for zones.
> Add support for `dnssec-policy`

- manifests/dnssec_policy.pp
- spec/defines/dns_dnssec_policy_spec.rb
- templates/named.dnssec_policy.epp
- types/dnssec_policy_key.pp
This is a complement to #205 to allow to setup custom policies.
This is currently a draft until I manage to deploy this code in a real-world workload.
> Add support for defining custom dnssec-policies

- manifests/init.pp
- manifests/params.pp
- spec/classes/dns_init_spec.rb
- templates/options.conf.erb
In BIND 9.15 the dnssec-enable config option was made obsolete (it's always enabled) and 9.18 removed it.
Fixes #207
> Handle dnssec-enable config option removal

- manifests/zone.pp
- spec/defines/dns_zone_spec.rb
- templates/zone.header.erb
See #196 
@ekohl Is it OK for you to manage zone without validation or would you prefer a more specific type (which would lead to a configuration more difficult to maintain) ?
Example :
- I created something like this (in Hiera)
```
dns::zones:
example.com:
replace_file: true
serial: 2
records:
- host1 IN A 192.168.0.1
- host2 IN A 192.168.0.2
```
- Or you want something like this (don't mind the naming, just for the format)
```
dns::zones:
example.com:
replace_file: true
serial: 2
records:
- name: host1
xx: IN
type: A
dst: 192.168.0.1
...
```
> Manage zone records

- manifests/zone.pp
evaluates if zone file is managed and zone file is not a forward, if the zone file is a forward type there is no value in creating the zone file as it will forward all requests.
There is a slim risk that someone may want a forward zone file that is forward first rather than forward only, upon research this usecase is obsolete in bind deployments and was a requirement due to some of the legacy capabilities in earlier versions of bind. 
If this risk is not an acceptable one to merge into the module, I can expand the evaluation to be zonetype and for include if the forward parameter is 'first' rather than 'only' which is the default for a foward zone.
I believe this is an acceptable use-case to ignore
> stopped zone file from being created if zone type is forward

- spec/classes/dns_init_spec.rb
This is more explicit in what happens.
> Use a better style in the test suite

- manifests/params.pp
- spec/classes/dns_init_spec.rb
validated against EL (Redhat / CentOS / Rocky) 7 - 8 - 9 functions correctly.
Basic test against Fedora 35, which also works
Adds check of EL version greater than 7 and sets dnssec_enable parameter to undef if greater to allow the removal of the parameter from options.conf, which is a deprecated parameter in EL8 and later. This removes any warning in 9.15 and any breakage in 9.18 or later. Any version EL 7 or earlier includes the parameter allowing the user to set it on and off depending on if they want to use it, but the parameter is included as a valid parameter
> Remove dnssec-enable option for EL >= 9

- manifests/logging/channel.pp
minor typo in syslog_facility error message from channel.pp detailing incorrect parameter
> logging channel error message typo faility to facility

- manifests/zone.pp
- spec/acceptance/dns_spec.rb
- spec/acceptance/logging_spec.rb
- spec/acceptance/views_spec.rb
- spec/defines/dns_logging_category_spec.rb
- spec/defines/dns_logging_channel_spec.rb
- spec/defines/dns_zone_spec.rb
- templates/options.conf.erb
We can now run puppet without legacy facts:
```
puppet config set include_legacy_facts false
```
When doing so, the module fail to get the default value for `$dns::zone::soa`.  Fix it by using the `networking.fqdn` fact.
While here, adjust a few more legacy facts.
> Remove legacy fact usage

- manifests/params.pp
- metadata.json
- spec/classes/dns_init_spec.rb
This change introduces initial support for Ubuntu Jammy.
Fixes: #227
> Add support for Ubuntu Jammy (22.04)

- manifests/logging/channel.pp
This produce a warning:
```
2023-11-19T05:33:05.421+02:00 WARN [qtp925335889-44] [puppetserver] Puppet Calling function empty() with Numeric value is deprecated. (file: /usr/local/etc/puppet/code/environments/production/modules/dns/manifests/logging/channel.pp, line: 61)
```
Since we have data-types in place (`Optional[Integer]`), we do not need
to care about an empty String.  Only `undef` will evaluate to false, and
it is the precise case we want to raise an error for.
> Fix calling function empty() with Numeric value

- manifests/init.pp
- manifests/zone.pp
- spec/classes/dns_init_spec.rb
- spec/defines/dns_zone_spec.rb
- templates/named.conf.erb
- templates/named.zone.erb
The statistics-channels statement declares communication channels to be used by system administrators to get access to statistics information of the name server. BIND will only start a listener if the directive is found in the configuration. The ACLs are rendered similar to the `controls` directive.
Statistics are not collected on a per-zone basis by default. To enable this behaviour, the defined type for zones has a new parameter to do so.
> add support for the statistics-channels directive

- manifests/zone.pp
- templates/named.zone.erb
This gives possibility to disable forwarding for delegated zone when server is authoritative for domain and global forwarding is set.
> Add support for empty forwarders in master zone

- manifests/init.pp
- manifests/view.pp
- manifests/zone.pp
- spec/type_aliases/forwarder_spec.rb
- types/forwarder.pp
A user can input an invalid value and the service will refuse to start up. We can catch this in data types, preventing service downtime.
> Fixes #37604 - Validate DNS forwarders

- manifests/init.pp
- spec/classes/dns_init_spec.rb
- templates/options.conf.erb
disable-empty-zone allows one to disable the automatically created zones
Fixes: #255
> Add parameter to set disable-empty-zone option

- manifests/install.pp
- metadata.json
The `ensure_packages()` function is deprecated with stdlib 9. It triggers a catalog compilation warning on Puppet 7 and a catgalog compilation error on Pupppet 8. This PR switches to the successor, `stdlib::ensure_packages()`. This function got introduced in stdlib 9.
> Update ensure_packages->stdlib::ensure_packages; require stdlib 9

- .github/workflows/ci.yml
- .sync.yml
- metadata.json
Added AlmaLinux 8 and 9 to the supported operating systems in metadata.json.
These changes ensure that we start testing with AlmaLinux 8 and 9 instead of CentOS 8 Stream. This update is part of our transition to better support AlmaLinux in our Puppet modules.
See, for details: https://github.com/theforeman/foreman-infra/issues/2087
> Add AlmaLinux 8 & 9 support

- lib/puppet/functions/dns/tsig_keygen.rb
- spec/functions/tsig_keygen_spec.rb
This wraps tsig-keygen and returns the data in a structured format. The result can be used to secure communications. It always generates a random key and the resulting data should be cached or otherwise made idempotent.
> Refs #37121 - Add dns::tsig_keygen function

- lib/puppet/functions/dns/dnssec_keygen.rb
- spec/functions/dnssec_keygen_spec.rb
This wraps dnssec-keygen and returns the data in a structured format. The result can be used to secure communications. It always generates a random key and the resulting data should be cached or otherwise made idempotent.
> Add dns::dnssec_keygen function

- manifests/params.pp
- metadata.json
- spec/classes/dns_init_spec.rb
These are end of life and testing on them isn't possible anymore.
> Drop RHEL 7, CentOS 7 & 8, Scientific 7 & Debian 10; Add RHEL 9 & Fedora 39 & 40

- manifests/params.pp
- spec/classes/dns_init_spec.rb
A security update on Ubuntu 20.04 brought BIND 9.18 which moves named-checkconf from /usr/sbin to /usr/bin.
This removes the need for the conditional because now all supported versions use /usr/bin.
> BIND 9.18 compatiblity on Ubuntu 20.04

- manifests/init.pp
- spec/classes/dns_init_spec.rb
- templates/options.conf.erb
... so that both listen-on and listen-on-v6 can be managed by the native parameters.
> Add parameter to control listen-on
